// Authentication Routes
export const AuthRoutes = {
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  AFFILIATE_REGISTER: "/register-as-affiliate",
};

// Authenticated Routes
export const AuthenticatedRoutes = {
  USER_DASHBOARD: "/auth",
  ADD_FUNDS: "/auth/add-funds",
  ADDED_FUNDS_HISTORY: "/auth/added-funds-history",
  PROFILE: "/auth/profile",
  MY_EARNINGS: "/auth/all-earnings",
  USER_ADD_FUNDS: "/auth/add-funds",
  ORDER_BY_FRANCHISE: "/auth/order-by-franchise",
  MY_ORDER: "/auth/my-order",
  WALLET: "/auth/wallet",
  WITHDRAWAL_REPORT: "/auth/withdrawal-report",
  MY_PAYOUT_REPORT: "/auth/may-payout-report",
  DIRECT_TEAM: "/auth/direct-team",
  LEVEL_WISE_MEMBERS: "/auth/level-wise-members",
  INVOICE: "/auth/invoice",
  ID_CARD: "/auth/id-card",
  MANAGE_PASSWORDS: "/auth/manage-passwords",
  REQUEST_FUND: "/auth/request-fund",
  TRANSFER_FUND: "/auth/transfer-fund",
  WELCOME_LETTER: "/auth/welcome-letter",
  HELP_SUPPORT: "/auth/help-support",
  MY_REWARDS: "/auth/my-rewards",
  CONSISTENCY_BONUS: "/auth/consistency-bonus",
  BONANZA_BONUS: "/auth/bonanza-bonus",
  LEADERSHIP_BONUS: "/auth/leadership-bonus",
  WITHDRAWAL: "/auth/withdrawal",
  TRANSACTION_REPORT: "/auth/transaction-report",
  PURCHASE_FRANCHISE: "/auth/franchise-store",
  PROMOTIONAL_TOOLS: "/auth/promotional-tools",
  REFER_AND_EARN: "/auth/refer-and-earn",
  DOWNLINE_TREE: "/auth/downline-tree",
  PORTFOLIO: "/auth/portfolio",
  MEMBERSHIP_PACKAGES: "/auth/membership-packages",
};

export const EcomRoutes = {
  PRODUCT_DETAIL: "/product/:productId",
  ALL_CATEGORIES: "/all-categories",
  VIEW_CART: "/view-cart",
  CHECKOUT: "/checkout",
  ALL_PRODUCTS: "/all-products",
  OUR_COMPANY: "/about-us",
  ALL_SERVICES: "/services",
  SERVICE_DETAIL: "/services/:id",
  BEST_SELLERS: "/best-sellers",
  TERMS_AND_CONDITIONS: "/terms-and-conditions",
  JOIN_US: "/join-us",
  CONTACT_US: "/contact-us",
  ABOUT_US: "/about-us",
  FAQ: "/faq",
  ORDER_SUCCESS: "/order-success",
  HOME: "/home",
  Landing:"/",
  Shop:"/shop",
  Blog:"/blog",
  Mega:"/mega",
  About:"/about",
  Contact:"/contact"
  
};
