export const genderOptions = [
  { label: "Male", value: "MALE" },
  { label: "Female", value: "FEMALE" },
  { label: "Other", value: "OTHER" },
  { label: "Prefer not to say", value: "PREFER_NOT_TO_SAY" },
];
export const relationOptions = [
  { label: "Father", value: "father" },
  { label: "Mother", value: "mother" },
  { label: "Husband", value: "husband" },
  { label: "Wife", value: "wife" },
  { label: "Son", value: "son" },
  { label: "Daughter", value: "daughter" },
  { label: "Other", value: "other" },
];

export const stateOptions = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Ladakh"
];

export const cityNameOptions = {
  "Andaman and Nicobar Islands": [
    "Port Blair",
    "Havelock Island",
    "Neil Island",
    "Car Nicobar",
    "Diglipur",
    "Rangat",
    "Mayabunder",
    "Baratang Island",
    "Kachal",
    "Kamorta",
  ],
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Tirupati",
    "Rajahmundry",
    "Kakinada",
    "Nellore",
    "Kadapa",
    "Anantapur",
    "Kurnool",
  ],
  "Arunachal Pradesh": [
    "Itanagar",
    "Naharlagun",
    "Pasighat",
    "Tawang",
    "Bomdila",
    "Tezu",
    "Ziro",
    "Roing",
    "Namsai",
    "Along",
  ],
  Assam: [
    "Guwahati",
    "Dibrugarh",
    "Silchar",
    "Jorhat",
    "Nagaon",
    "Tezpur",
    "Karimganj",
    "Bongaigaon",
    "Haflong",
    "Sibsagar",
  ],
  Bihar: [
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzzaffarpur",
    "Purnea",
    "Chapra",
    "Arrah",
    "Darbhanga",
    "Sasaram",
    "Siwan",
  ],
  Chandigarh: ["Chandigarh"],
  Chhattisgarh: [
    "Raipur",
    "Bhilai",
    "Durg",
    "Bilaspur",
    "Korba",
    "Jagdalpur",
    "Raigarh",
    "Ambikapur",
    "Bastar",
    "Mahasamund",
  ],
  "Dadra and Nagar Haveli and Daman and Diu": [
    "Silvassa",
    "Daman",
    "Diu",
  ],
  Delhi: ["Delhi"],
  Goa: ["Panaji", "Margao", "Vasco da Gama"],
  Gujarat: [
    "Ahmedabad",
    "Vadodara",
    "Surat",
    "Rajkot",
    "Gandhinagar",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Mehsana",
    "Anand",
  ],
  Haryana: [
    "Faridabad",
    "Gurugram",
    "Ambala",
    "Hisar",
    "Karnal",
    "Panipat",
    "Rohtak",
    "Yamunanagar",
    "Sirsa",
    "Jind",
  ],
  "Himachal Pradesh": [
    "Shimla",
    "Manali",
    "Dharamshala",
    "Kullu",
    "Solan",
    "Mandi",
    "Hamirpur",
    "Una",
    "Bilaspur",
    "Palampur",
  ],
  "Jammu and Kashmir": [
    "Srinagar",
    "Jammu",
    "Anantnag",
    "Baramulla",
    "Kathua",
    "Udhampur",
    "Pulwama",
    "Rajouri",
    "Kupwara",
    "Doda",
  ],
  Jharkhand: [
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro",
    "Hazaribagh",
    "Giridih",
    "Deoghar",
    "Chaibasa",
    "Dumka",
    "Koderma",
  ],
  Karnataka: [
    "Bengaluru",
    "Mysuru",
    "Hubli",
    "Dharwad",
    "Mangalore",
    "Belagavi",
    "Tumkur",
    "Udupi",
    "Bagalkot",
    "Gulbarga",
  ],
  Kerala: [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Kannur",
    "Palakkad",
    "Thrissur",
    "Alappuzha",
    "Kottayam",
    "Malappuram",
    "Wayanad",
  ],
  Lakshadweep: ["Kavaratti", "Agatti", "Andrott", "Minicoy"],
  "Madhya Pradesh": [
    "Bhopal",
    "Indore",
    "Gwalior",
    "Jabalpur",
    "Ujjain",
    "Sagar",
    "Rewa",
    "Satna",
    "Dewas",
    "Ratlam",
    "Khandwa",
    "Khargone",
    "Chhindwara",
    "Mandla",
    "Sehore",
    "Shivpuri",
    "Hoshangabad",
    "Vidisha",
    "Mandsaur",
    "Burhanpur",
  ],
  Maharashtra: [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Aurangabad",
    "Nashik",
    "Thane",
    "Solapur",
    "Amravati",
    "Kolhapur",
    "Jalgaon",
  ],
  Manipur: [
    "Imphal",
    "Thoubal",
    "Ukhrul",
    "Churachandpur",
    "Bishnupur",
    "Jiribam",
    "Senapati",
    "Tamenglong",
    "Kakching",
    "Kangpokpi",
  ],
  Meghalaya: [
    "Shillong",
    "Tura",
    "Jowai",
    "Nongpoh",
    "Williamnagar",
    "Bholaganj",
    "Mairang",
    "Baghmara",
    "Rongram",
    "Jaintia Hills",
  ],
  Mizoram: [
    "Aizawl",
    "Lunglei",
    "Champhai",
    "Serchhip",
    "Lawngtlai",
    "Saiha",
    "Kolasib",
    "Mamit",
    "Saitual",
    "Khawzawl",
  ],
  Nagaland: [
    "Kohima",
    "Dimapur",
    "Wokha",
    "Mokokchung",
    "Zunheboto",
    "Tuensang",
    "Phek",
    "Mon",
    "Longleng",
    "Kiphire",
  ],
  Odisha: [
    "Bhubaneswar",
    "Cuttack",
    "Berhampur",
    "Rourkela",
    "Sambalpur",
    "Balasore",
    "Koraput",
    "Jeypore",
    "Angul",
    "Dhenkanal",
  ],
  Puducherry: ["Puducherry", "Karaikal", "Yanam", "Mahe"],
  Punjab: [
    "Chandigarh",
    "Amritsar",
    "Ludhiana",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Mohali",
    "Hoshiarpur",
    "Firozpur",
    "Rupnagar",
  ],
  Rajasthan: [
    "Jaipur",
    "Udaipur",
    "Jodhpur",
    "Kota",
    "Bikaner",
    "Ajmer",
    "Alwar",
    "Sikar",
    "Jhunjhunu",
    "Pali",
  ],
  Sikkim: ["Gangtok", "Namchi", "Gyalshing", "Mangan"],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Trichy",
    "Salem",
    "Tirunelveli",
    "Erode",
    "Vellore",
    "Tirupur",
    "Ramanathapuram",
  ],
  Telangana: [
    "Hyderabad",
    "Warangal",
    "Karimnagar",
    "Nizamabad",
    "Khammam",
    "Mahbubnagar",
    "Nalgonda",
    "Ramagundam",
    "Adilabad",
    "Jogulamba Gadwal",
  ],
  Tripura: [
    "Agartala",
    "Ambassa",
    "Udaipur",
    "Belonia",
    "Khowai",
    "Dharmanagar",
    "Melaghar",
    "Santirbazar",
    "Teliamura",
    "Sabroom",
  ],
  "Uttar Pradesh": [
    "Lucknow",
    "Kanpur",
    "Agra",
    "Varanasi",
    "Allahabad",
    "Ghaziabad",
    "Noida",
    "Meerut",
    "Mathura",
    "Bareilly",
  ],
  Uttarakhand: [
    "Dehradun",
    "Haridwar",
    "Roorkee",
    "Rishikesh",
    "Nainital",
    "Pithoragarh",
    "Almora",
    "Kashipur",
    "Haldwani",
    "Rudrapur",
  ],
  "West Bengal": [
    "Kolkata",
    "Howrah",
    "Siliguri",
    "Durgapur",
    "Asansol",
    "Kharagpur",
    "Bardhaman",
    "Jalpaiguri",
    "Malda",
    "Cooch Behar",
  ],
  Ladakh: ["Leh", "Kargil"],
};

export const countryOptions = [
  { label: "India", value: "India" },
  { label: "USA", value: "USA" },
  { label: "UK", value: "UK" },
  { label: "Canada", value: "Canada" },
  { label: "Australia", value: "Australia" },
  { label: "Germany", value: "Germany" },
  { label: "France", value: "France" },
  { label: "Japan", value: "Japan" },
];

export const legOptions = [
  { label: "Left Leg", value: "LEFT" },
  { label: "Right Leg", value: "RIGHT" },
];

// marital status options
export const maritalStatusOptions = [
  { label: "Single", value: "SINGLE" },
  { label: "Married", value: "MARRIED" },
  { label: "Divorced", value: "DIVORCED" },
  { label: "Widowed", value: "WIDOWED" },
  { label: "Separated", value: "SEPARATED" },
];
//

export const BankNameList = [
  "Allahabad Bank (Merged with Indian Bank)",
  "ANZ Grindlays Bank",
  "Axis Bank",
  "Bank of Baroda (BoB)",
  "Bank of Baroda - Corporate Banking",
  "Bank of Baroda - Retail Banking",
  "Bank of India (BoI)",
  "Bank of Maharashtra (BoM)",
  "Bandhan Bank",
  "Barclays Bank",
  "BNP Paribas",
  "Canara Bank",
  "Central Bank of India",
  "Citibank",
  "City Union Bank",
  "Corporation Bank",
  "Deutsche Bank",
  "Development Credit Bank",
  "Dhanlaxmi Bank",
  "Federal Bank",
  "HSBC",
  "HSBC India (Foreign Bank)",
  "ICICI Bank",
  "IDBI Bank",
  "IDFC FIRST Bank",
  "Indian Bank",
  "Indian Overseas Bank (IOB)",
  "IndusInd Bank",
  "ING Vysya Bank",
  "Jammu & Kashmir Bank",
  "JPMorgan Chase",
  "Karnataka Bank Ltd",
  "Karur Vysya Bank",
  "Kotak Mahindra Bank",
  "Lakshmi Vilas Bank (Merged with DBS Bank India)",
  "National Bank for Agriculture and Rural Development (NABARD)",
  "Nabard (National Bank for Agriculture and Rural Development)",
  "Oriental Bank of Commerce (Merged with PNB)",
  "Punjab National Bank (PNB)",
  "Punjab National Bank - Corporate Banking",
  "Punjab National Bank - Retail Banking",
  "Punjab & Sind Bank",
  "RBL Bank",
  "Shamrao Vitthal Co-operative Bank",
  "Shamrao Vithal Co-operative Bank (SVC)",
  "Small Industries Development Bank of India (SIDBI)",
  "South Indian Bank",
  "Standard Chartered Bank",
  "Standard Chartered Bank (Foreign Bank)",
  "State Bank of Bikaner & Jaipur",
  "State Bank of Hyderabad",
  "State Bank of India",
  "State Bank of Mysore",
  "State Bank of Patiala",
  "State Bank of Travancore",
  "Syndicate Bank (Merged with Canara Bank)",
  "Tamilnad Mercantile Bank (TMB)",
  "Tamilnad Mercantile Bank Ltd.",
  "UBS",
  "Union Bank of India",
  "UCO Bank",
  "United Bank of India",
  "Vijaya Bank (Merged with Bank of Baroda)",
  "Yes Bank",
  "Yes Bank Ltd",
];

// relationship options
export const relationshipOptions = [
  { label: "Father", value: "FATHER" },
  { label: "Mother", value: "MOTHER" },
  { label: "Spouse", value: "SPOUSE" },
  { label: "Son", value: "SON" },
  { label: "Daughter", value: "DAUGHTER" },
  { label: "Brother", value: "BROTHER" },
  { label: "Sister", value: "SISTER" },
  { label: "Other", value: "OTHER" },
];
